baseURL = "https://emmajane.net/"
languageCode = "en-uk"
title = "emmajane.net"
publishdir = "docs"

theme = "ezhil"
[params]
  mode = "dark"
  mainSections = ["running"]
  subtitle = "The hardest thing I do each day is imagine who I want to become."

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about/emma"
weight = 2
